---
"/parameters":
  get:
    tags:
    - parameters
    description: CHANGEME_LONG.
    summary: CHANGEME_SHORT
    parameters: []
    operationId: CHANGEME-GetParameters
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
"/parameters/{component}":
  get:
    tags:
    - parameters
    description: CHANGEME_LONG.
    summary: CHANGEME_SHORT
    parameters:
    - in: path
      name: component
      required: true
      schema:
        type: string
        description: CHANGEME.
    operationId: CHANGEME-GetParameters
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
"/parameters/{component}/{vhost}":
  get:
    tags:
    - parameters
    description: CHANGEME_LONG.
    summary: CHANGEME_SHORT
    parameters:
    - in: path
      name: component
      required: true
      schema:
        type: string
        description: CHANGEME.
    - in: path
      name: vhost
      required: true
      schema:
        type: string
        description: CHANGEME.
    operationId: CHANGEME-GetParameters
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
"/parameters/{component}/{vhost}/{name}":
  get:
    tags:
    - parameters
    description: CHANGEME_LONG.
    summary: CHANGEME_SHORT
    parameters:
    - in: path
      name: component
      required: true
      schema:
        type: string
        description: CHANGEME.
    - in: path
      name: vhost
      required: true
      schema:
        type: string
        description: CHANGEME.
    - in: path
      name: name
      required: true
      schema:
        type: string
        description: CHANGEME.
    operationId: CHANGEME-GetParameters
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
  put:
    tags:
    - parameters
    description: CHANGEME_LONG.
    summary: CHANGEME_SHORT
    parameters:
    - in: path
      name: component
      required: true
      schema:
        type: string
        description: CHANGEME.
    - in: path
      name: vhost
      required: true
      schema:
        type: string
        description: CHANGEME.
    - in: path
      name: name
      required: true
      schema:
        type: string
        description: CHANGEME.
    operationId: CHANGEME-PutParameters
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
  delete:
    tags:
    - parameters
    description: CHANGEME_LONG.
    summary: CHANGEME_SHORT
    parameters:
    - in: path
      name: component
      required: true
      schema:
        type: string
        description: CHANGEME.
    - in: path
      name: vhost
      required: true
      schema:
        type: string
        description: CHANGEME.
    - in: path
      name: name
      required: true
      schema:
        type: string
        description: CHANGEME.
    operationId: CHANGEME-DeleteParameters
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
"/global-parameters":
  get:
    tags:
    - parameters
    description: CHANGEME_LONG.
    summary: CHANGEME_SHORT
    parameters: []
    operationId: CHANGEME-GetParameters
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
"/global-parameters/{name}":
  get:
    tags:
    - parameters
    description: CHANGEME_LONG.
    summary: CHANGEME_SHORT
    parameters:
    - in: path
      name: name
      required: true
      schema:
        type: string
        description: CHANGEME.
    operationId: CHANGEME-GetParameters
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
  put:
    tags:
    - parameters
    description: CHANGEME_LONG.
    summary: CHANGEME_SHORT
    parameters:
    - in: path
      name: name
      required: true
      schema:
        type: string
        description: CHANGEME.
    operationId: CHANGEME-PutParameters
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
  delete:
    tags:
    - parameters
    description: CHANGEME_LONG.
    summary: CHANGEME_SHORT
    parameters:
    - in: path
      name: name
      required: true
      schema:
        type: string
        description: CHANGEME.
    operationId: CHANGEME-DeleteParameters
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
"/policies":
  get:
    tags:
    - parameters
    description: CHANGEME_LONG.
    summary: CHANGEME_SHORT
    parameters: []
    operationId: CHANGEME-GetParameters
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
"/policies/{vhost}":
  get:
    tags:
    - parameters
    description: CHANGEME_LONG.
    summary: CHANGEME_SHORT
    parameters:
    - in: path
      name: vhost
      required: true
      schema:
        type: string
        description: CHANGEME.
    operationId: CHANGEME-GetParameters
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
"/policies/{vhost}/{name}":
  get:
    tags:
    - parameters
    description: CHANGEME_LONG.
    summary: CHANGEME_SHORT
    parameters:
    - in: path
      name: vhost
      required: true
      schema:
        type: string
        description: CHANGEME.
    - in: path
      name: name
      required: true
      schema:
        type: string
        description: CHANGEME.
    operationId: CHANGEME-GetParameters
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
  put:
    tags:
    - parameters
    description: CHANGEME_LONG.
    summary: CHANGEME_SHORT
    parameters:
    - in: path
      name: vhost
      required: true
      schema:
        type: string
        description: CHANGEME.
    - in: path
      name: name
      required: true
      schema:
        type: string
        description: CHANGEME.
    operationId: CHANGEME-PutParameters
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
  delete:
    tags:
    - parameters
    description: CHANGEME_LONG.
    summary: CHANGEME_SHORT
    parameters:
    - in: path
      name: vhost
      required: true
      schema:
        type: string
        description: CHANGEME.
    - in: path
      name: name
      required: true
      schema:
        type: string
        description: CHANGEME.
    operationId: CHANGEME-DeleteParameters
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
"/operator-policies":
  get:
    tags:
    - parameters
    description: CHANGEME_LONG.
    summary: CHANGEME_SHORT
    parameters: []
    operationId: CHANGEME-GetParameters
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
"/operator-policies/{vhost}":
  get:
    tags:
    - parameters
    description: CHANGEME_LONG.
    summary: CHANGEME_SHORT
    parameters:
    - in: path
      name: vhost
      required: true
      schema:
        type: string
        description: CHANGEME.
    operationId: CHANGEME-GetParameters
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
"/operator-policies/{vhost}/{name}":
  get:
    tags:
    - parameters
    description: CHANGEME_LONG.
    summary: CHANGEME_SHORT
    parameters:
    - in: path
      name: vhost
      required: true
      schema:
        type: string
        description: CHANGEME.
    - in: path
      name: name
      required: true
      schema:
        type: string
        description: CHANGEME.
    operationId: CHANGEME-GetParameters
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
  put:
    tags:
    - parameters
    description: CHANGEME_LONG.
    summary: CHANGEME_SHORT
    parameters:
    - in: path
      name: vhost
      required: true
      schema:
        type: string
        description: CHANGEME.
    - in: path
      name: name
      required: true
      schema:
        type: string
        description: CHANGEME.
    operationId: CHANGEME-PutParameters
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
  delete:
    tags:
    - parameters
    description: CHANGEME_LONG.
    summary: CHANGEME_SHORT
    parameters:
    - in: path
      name: vhost
      required: true
      schema:
        type: string
        description: CHANGEME.
    - in: path
      name: name
      required: true
      schema:
        type: string
        description: CHANGEME.
    operationId: CHANGEME-DeleteParameters
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/parameters"
      4XX:
        description: Client Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
      5XX:
        description: Server Error
        content:
          application/json:
            schema:
              "$ref": "../openapi.yaml#/components/schemas/ErrorResponse"
