freebsd_task:
  skip: "!changesInclude('.cirrus.yml', 'shard.lock', 'src/**', 'spec/**', 'views/**')"
  freebsd_instance:
    image_family: freebsd-14-0-snap
  install_script: pkg install -y crystal shards security/openssl curl gmake
  spec_script: gmake test random=1 nocolor=1
  build_script: gmake -j2 DOCS=
  artifacts:
    path: bin/*

osx_task:
  skip: "!changesInclude('.cirrus.yml', 'shard.lock', 'src/**', 'spec/**', 'views/**')"
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest
  install_script:
    - brew update
    - brew install crystal
  spec_script: make test nocolor=1 random=1
  env:
    PKG_CONFIG_PATH: /usr/local/opt/openssl@1.1/lib/pkgconfig
  build_script: make -j2 DOCS=
  artifacts:
    path: bin/*

arm_task:
  skip: "!changesInclude('.cirrus.yml', 'shard.lock', 'src/**', 'spec/**', 'views/**')"
  arm_container:
    image: 84codes/crystal:latest-ubuntu-22.04
    cpu: 2
    memory: 4G
    greedy: true
  spec_script: make test random=1
