#!/bin/sh

set -e

./create_avalanchemq_version_yaml

echo "View the docs at http://localhost:8080/"

docker run -it --rm -p 8080:80 \
  -v $(pwd):/usr/share/nginx/html/swagger/ \
  -e SPEC_URL=swagger/openapi.yaml redocly/redoc
