#!/bin/sh

set -eu

ROOT=${PWD%/*}

echo "View the docs at http://localhost:8080/"

set -x

docker run -it --rm -p 8080:80 \
  -v $ROOT:/usr/share/nginx/html/swagger/ \
  -e SPEC_URL=swagger/openapi/openapi.yaml redocly/redoc
