#!/bin/bash -eu
# Generates a version string from `git describe` in a format that RPM accepts
# https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/
last_tag=$(git describe --tags --abbrev=0)
version=$(cut -d- -f1 <<< ${last_tag:1})
pre_release=$(cut -d- -f2 -s <<< $last_tag)
if [ -n "$pre_release" ]
then version=$version~${pre_release//./}
fi
git_describe=$(git describe --tags)
post_release=${git_describe//$last_tag/}
post_release=${post_release:1}
post_release=${post_release//-/.}
if [ -n "$post_release" ]
then version=$version^${post_release}
fi
echo $version
