name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

# explicitly configure permissions, in case your GITHUB_TOKEN workflow permissions are set to read-only in repository settings
permissions:
  actions: write
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # gives write access to the remote repository
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_SIGNATURES_GITHUB_TOKEN }}
        with:
          path-to-signatures: 'signatures/lavinmq/cla.json'
          path-to-document: 'https://github.com/cloudamqp/CLA-signatures/blob/main/cla.md'
          # branch should not be protected
          branch: 'main'
          allowlist: 'dependabot[bot]'
          remote-organization-name: 'cloudamqp'
          remote-repository-name: 'CLA-signatures'
